# Generated by Django 4.2 on 2023-05-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='productos',
            new_name='product',
        ),
    ]
